name: Deployment Pipeline

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - uses: actions/setup-node@v2
        with:
          node-version: '18'  

      - run: npm install
        working-directory: .

      - run: npm install -g @railway/cli
        name: Install Railway CLI

      - run: railway up --service squealing-pet -- --token ${{ secrets.RAILWAY_TOKEN }}
        name: Deploy to Railway



